from pathlib import Path

DEFAULT_PATH_CONFIG = Path('config.json')
DEFAULT_PATH_DATA_DIR = Path('data')
DEFAULT_PATH_MERGED_DATA = DEFAULT_PATH_DATA_DIR / 'data'
DEFAULT_PATH_LANG_MODELS_DIR = DEFAULT_PATH_DATA_DIR / 'models'
DEFAULT_PATH_W2V_MODELS_DIR = DEFAULT_PATH_DATA_DIR / 'w2v'
DEFAULT_PATH_W2V_MODEL = lambda epochs, size: DEFAULT_PATH_W2V_MODELS_DIR / f'w2v_e{epochs}_s{size}.model'
DEFAULT_PATH_CORPUS = DEFAULT_PATH_DATA_DIR / 'corpus.txt'
