from pathlib import Path

DEFAULT_PATH_CONFIG = 'config.json'
DEFAULT_PATH_DATA_DIR = Path('data')
DEFAULT_PATH_MERGED_DATA = DEFAULT_PATH_DATA_DIR / 'data'
DEFAULT_PATH_PLAYLISTS = DEFAULT_PATH_DATA_DIR / 'playlists'
DEFAULT_PATH_TRACKS = DEFAULT_PATH_DATA_DIR / 'tracks'
DEFAULT_PATH_LANG_MODELS_DIR = DEFAULT_PATH_DATA_DIR / 'models'
DEFAULT_PATH_TRACKS_LYRICS = DEFAULT_PATH_DATA_DIR / 'lyrics'
